baseURL : "http://hulkvision.gitlab.io" #copy-paste your domain here
languageCode : "en" #used in SEO tags
title : "hulkvision's Blog" #actual title of the site used in browser tabs as well as SEO
theme : "anatole" #name of the directory containing theme files
summarylength : 50 #summary length shown on list pages
enableRobotsTXT : true #leave true for SEO
#this file instructs search engine crawlers on how to acess the site

params:
  title : "Hi! I'm Sunny 👋Welcome!" #emphasised  line on the homepage
  author : "Sunny Gupta"
  copyright : "2022" #copyright text in the footer
 # description : "Call me Sunny" #introduction line on homepage
  profilePicture : "profile.png" #the name of the profile img to be displayed (relative to the static folder)
  keywords : "" #seo keywords for your homepage
  #favicons are small images displayed in the browser tab similar to app icons
  favicon : "favicons/" #directory name holding the favicons (relative to the static folder)
  mainSections : ["blog"]
  #which folder to use to list posts on the homepage (relative to the content dir)
  images : ["featured-image.png"] #image used for social media previews
  doNotLoadAnimations : false #set to true to disable animations
  postSectionName : "blog" #the slug of the "archives" listing page
  #uncomment this if you want your site to load in dark-mode by default.
  # displayMode: "dark"

  ## Social links
  #the icons are loaded from font-awesome library
  #find the icon codes here: https://fontawesome.com/icons?d=gallery&p=2
  # use 'fab' when brand icons, use 'fas' when standard solid icons.
  socialIcons:
    - icon : "fab fa-twitter"
      title : "Twitter"
      url : "https://twitter.com/hulkvision"
    # - icon : "fab fa-github"
    #   title : "GitHub"
    #   url : "https://github.com/hulkvision/"
    - icon : "fab fa-linkedin"
      title : "Linkedin"
      url : "https://www.linkedin.com/in/hulkvision/"
    - icon : "fas fa-envelope"
      title : "e-mail"
      url : "mailto:hulkvision@protonmail.com"

  # Google Search Console Verification
  #googleSiteVerify : "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"
  # Read More links for truncated summaries
  # readMore : true

  ## Math settings
  math:
    enable : false  # options: true, false.

## Menu items
#weight defines which entry is shown first
menu:
  main:
    - name : "Home"
      identifier : "home"
      weight : 100
      url : "/"
    - name : "Archives"
      weight : 200
      identifier : "archives"
      url : "/blog"
    - name : "About"
      weight : 300
      identifier : "about"
      url : "/about"

taxonomies:
  category: categories
  series: series
  tag: tags

timeout: 30000
#required to exit out of long posts requiring lot of processing.

minify:
  disableXML: true
  minifyOutput: false

# Google Analytics
# Hugo supports GA4 V8.20 (latest at the time of writing) onwards.
#googleAnalytics : "UA-123-45"

publishDir: "docs"
